repos:
  - repo: 'https://github.com/Scony/godot-gdscript-toolkit'
    rev: 3.4.0
    hooks:
      - id: gdlint
        name: gdlint
        description: gdlint - linter for GDScript
        entry: gdlint
        language: python
        language_version: python3
        require_serial: true
        types:
          - gdscript
      - id: gdformat
        args: ["--line-length=119"]
        name: gdformat
        description: gdformat - formatter for GDScript
        entry: gdformat
        language: python
        language_version: python3
        require_serial: true
        types:
          - gdscript
